name: Upload Artifact

on: 
  push:
  workflow_dispatch: 
  
env:
  TRIGGER: ${{ github.event_name }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout..
              uses: actions/checkout@v4.1.1
              
            - name: Build artifact
              uses: actions/upload-artifact@v4
              with:
                path: ./

            - name: Download artifact
              uses: actions/download-artifact@v4 
            

            - name: Send to Nexus/dev repository
              if  : ${{ env.TRIGGER }} == 'push'
              run : curl --fail -u ${{secrets.NEXUS_UNAME}}:${{secrets.NEXUS_PSW}} --upload-file artifact  'https://d97f-46-162-196-212.ngrok-free.app/repository/dev/'
            - name: Send to Nexus/test repo  
              if  : ${{ env.TRIGGER }} == 'workflow_dispatch'
              run : curl --fail -u ${{secrets.NEXUS_UNAME}}:${{secrets.NEXUS_PSW}} --upload-file artifact  'https://d97f-46-162-196-212.ngrok-free.app/repository/test/'
