name: Upload Artifact

on: 
  release: 
  
env:
  VERSION_TAG: ${{ github.event.release.tag_name}}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout..
              uses: actions/checkout@v4.1.1

            - name: See release-tag
              run : echo ${{ env.TRIGGER }}
              
            - name: Build artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.VERSION_TAG }}
                path: ./

            - name: Download artifact
              uses: actions/download-artifact@v4
              

            - name: Send to Nexus/prod repository
              run : curl --fail -u ${{secrets.NEXUS_UNAME}}:${{secrets.NEXUS_PSW}} --upload-file ${{env.VERSION_TAG}}  'https://d97f-46-162-196-212.ngrok-free.app/repository/prod/'
